x = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(x))
print('Só tem espaços?', x.isspace())
print('É um numero?', x.isnumeric())
print('É alfabético?', x.isalpha())
print('É alfanumérico?', x.isascii())
print('Está em maiusculas?', x.isupper())
print('Está em minusculas?', x.islower())
print('Está capitalizada?', x.istitle())
