n = str(input('Digite seu nome completo: ')).strip()
nome = n.split()
first = (nome[0])
last = (nome[len(nome)-1])
print('Muito prazer em te conhecer! ૮₍ ˶ᵔ ᵕ ᵔ˶ ₎ა')
print('Seu primeiro nome é {} e seu ultimo nome é {}.'.format(first, last))
